### ISSUE TITLE
userBlockQuery : Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by skys215** [Latrell/RongCloud#1]
[RongCloud/RongCloud.php L42](https://github.com/latrell/RongCloud/blob/master/src/Latrell/RongCloud/RongCloud.php#L42)
不知道是出现了什么问题。

**Comment by latrell** [comment]
看上去是融云SDK的BUG。
[$ret = $this->curl('/user/block/query',''); // 第二个参数应该为数组类型。](https://github.com/rongcloud/server-sdk-php-composer/blob/master/src/RongCloud/Api.php#L774)
