### ISSUE TITLE
class 'RongCloud\Api' does not have a method 'chatroomJoin'

### ISSUE THREAD

**Issue by skys215** [Latrell/RongCloud#2]
[加入聊天室](http://www.rongcloud.cn/docs/server.html#加入聊天室_方法)
没有加入聊天室的方法？

**Comment by skys215** [comment]
我好像要在融云那边提bug，而不是在你这边，抱歉。

**Comment by latrell** [comment]
我这个只是对融云的SDK进行一层封装，让它可以方便的在Laravel框架下使用，只是层壳而已。
